<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>kui</string>
		</array>
		<key>name</key>
		<string>kui</string>
		<key>scopeName</key>
		<string>text.kui.basic</string>
		<key>repository</key>
		<dict>
			<key>string</key>
			<dict>
				<key>name</key>
				<string>string</string>
				<key>match</key>
				<string>".*?"</string>
			</dict>
			<key>translate-string</key>
			<dict>
				<key>name</key>
				<string>constant.character.escape</string>
				<key>match</key>
				<string>\$".*?"</string>
			</dict>
			<key>vector</key>
			<dict>
				<key>name</key>
				<string>constant.numeric</string>
				<key>match</key>
				<string>\(.*?\)(ar|sr|px|rgb|)</string>
			</dict>
			<key>size</key>
			<dict>
				<key>name</key>
				<string>constant.numeric</string>
				<key>match</key>
				<string>\b(\d+\.\d+|\d+)(ar|sr|px|)\b</string>
			</dict>
			<key>namedValue</key>
			<dict>
				<key>name</key>
				<string>constant.language</string>
				<key>match</key>
				<string>\b(true|false|horizontal|vertical|default|reverse|centered)\b</string>
			</dict>
			<key>value</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#string</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#translate-string</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#vector</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#size</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#namedValue</string>
					</dict>
				</array>
			</dict>
			<key>scope</key>
			<dict>
				<key>begin</key>
				<string>{</string>
				<key>end</key>
				<string>}</string>
				<key>beginCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.bracket.begin</string>
					</dict>
				</array>
				<key>endCaptures</key>
				<array>
					<dict>
						<key>name</key>
						<string>punctuation.bracket.end</string>
					</dict>
				</array>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#scope</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#declare-var</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#var</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#scope-assign-param</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#comment</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#declare-child</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#child</string>
					</dict>
				</array>
			</dict>
			<key>scope-assign-param</key>
			<dict>
				<key>name</key>
				<string>meta.assign</string>
				<key>begin</key>
				<string>\b\w+\s*?=</string>
				<key>end</key>
				<string>(;|$)</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>name</key>
								<string>variable</string>
								<key>match</key>
								<string>\w+</string>
							</dict>
						</array>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#value</string>
					</dict>
				</array>
			</dict>
			<key>declare-element</key>
			<dict>
				<key>name</key>
				<string>meta.element</string>
				<key>match</key>
				<string>\belement\s+?\w+?\b</string>
				<key>captures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#element</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#type</string>
							</dict>
						</array>
					</dict>
				</dict>
			</dict>
			<key>declare-const</key>
			<dict>
				<key>name</key>
				<string>meta.const</string>
				<key>match</key>
				<string>\b(const|global)\s+\w+\s*?(=\s*?(.*?)??)??(;|$)</string>
				<key>captures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#const-assign</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#value</string>
							</dict>
						</array>
					</dict>
				</dict>
			</dict>
			<key>declare-var</key>
			<dict>
				<key>name</key>
				<string>meta.var</string>
				<key>match</key>
				<string>\bvar\s+\w+\s*?(=\s*?(.*?)??)??(;|$)</string>
				<key>captures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#var-assign</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#value</string>
							</dict>
						</array>
					</dict>
				</dict>
			</dict>
			<key>declare-child</key>
			<dict>
				<key>name</key>
				<string>meta.declare_child</string>
				<key>match</key>
				<string>\bchild\s+\w+\s*?</string>
				<key>captures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#child</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#type</string>
							</dict>
						</array>
					</dict>
				</dict>
			</dict>
			<key>const-assign</key>
			<dict>
				<key>match</key>
				<string>\b(const|global)\s*?\w+?\b</string>
				<key>captures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#const</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#variable</string>
							</dict>
						</array>
					</dict>
				</dict>
			</dict>
			<key>var-assign</key>
			<dict>
				<key>match</key>
				<string>\bvar\s+\w+?\b</string>
				<key>captures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#var</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#variable</string>
							</dict>
						</array>
					</dict>
				</dict>
			</dict>
			<key>type</key>
			<dict>
				<key>name</key>
				<string>support.class</string>
				<key>match</key>
				<string>\b\w+?\b</string>
			</dict>
			<key>variable</key>
			<dict>
				<key>name</key>
				<string>variable</string>
				<key>match</key>
				<string>\b\w+?\b</string>
			</dict>
			<key>element</key>
			<dict>
				<key>name</key>
				<string>keyword</string>
				<key>match</key>
				<string>\belement\b</string>
			</dict>
			<key>child</key>
			<dict>
				<key>name</key>
				<string>keyword</string>
				<key>match</key>
				<string>\bchild\b</string>
			</dict>
			<key>const</key>
			<dict>
				<key>name</key>
				<string>keyword</string>
				<key>match</key>
				<string>\b(const|global)\b</string>
			</dict>
			<key>var</key>
			<dict>
				<key>name</key>
				<string>keyword</string>
				<key>match</key>
				<string>\bvar\b</string>
			</dict>
			<key>comment</key>
			<dict>
				<key>name</key>
				<string>comment.line</string>
				<key>match</key>
				<string>//.*?$</string>
			</dict>
		</dict>
		<key>patterns</key>
		<array>
			<dict>
				<key>include</key>
				<string>#declare-element</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#element</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#declare-const</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#scope</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#comment</string>
			</dict>
		</array>
		<key>uuid</key>
		<string>BCDAD0EB-2940-4CFE-BD8E-741445ECC18A</string>
	</dict>
</plist>
